spring:
  application:
    name: registry
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      username: root
      password: secret
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0